version: '3'
services:
  elk:
   image: hellonico/elk
   ports:
     - "5601:5601"
     - "9200:9200"
     - "5044:5044"
   environment:
     ES_HEAP_SIZE: "2g"
     LS_HEAP_SIZE: "1g"
   volumes:
     - "./logs:/var/logs"